# Generated by Django 3.1.7 on 2021-04-09 05:18

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(default='default', max_length=255)),
                ('address', models.CharField(default='default', max_length=255)),
                ('latitude', models.DecimalField(decimal_places=7, default=0.0, max_digits=30)),
                ('longitude', models.DecimalField(decimal_places=7, default=0.0, max_digits=30)),
                ('category', models.CharField(default='default', max_length=255)),
                ('hours', models.CharField(default='default', max_length=255)),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('description', models.TextField(default='default')),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(default='default', max_length=255)),
                ('quantity', models.IntegerField(default=1)),
                ('category', models.CharField(default='Food', max_length=255)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('imgURL', models.CharField(default='https://image.shutterstock.com/image-photo/top-view-three-yellow-bananas-260nw-1875848530 .jpg', max_length=255)),
                ('vendor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='store.vendor')),
            ],
        ),
    ]
