# Generated by Django 3.1.7 on 2021-04-09 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_remove_vendor_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='category',
            field=models.CharField(default='Groccery Store', max_length=255),
            preserve_default=False,
        ),
    ]
