# Generated by Django 3.0.3 on 2021-03-10 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_account_address_nutrition_order_shoppingcart_vendor'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='category',
            field=models.CharField(default='default', max_length=255),
        ),
        migrations.AddField(
            model_name='vendor',
            name='description',
            field=models.TextField(default='default'),
        ),
        migrations.AddField(
            model_name='vendor',
            name='hours',
            field=models.CharField(default='default', max_length=255),
        ),
        migrations.AddField(
            model_name='vendor',
            name='latitude',
            field=models.DecimalField(decimal_places=7, default=0.0, max_digits=30),
        ),
        migrations.AddField(
            model_name='vendor',
            name='longitude',
            field=models.DecimalField(decimal_places=7, default=0.0, max_digits=30),
        ),
        migrations.AddField(
            model_name='vendor',
            name='phone',
            field=models.CharField(default='default', max_length=255),
        ),
    ]
