# Generated by Django 3.1.7 on 2021-03-16 20:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20210316_2037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='shoppingCart',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.shoppingcart'),
        ),
    ]
