# Generated by Django 3.1.7 on 2021-03-24 03:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20210323_1836'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor',
            name='inventory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.item'),
        ),
    ]
