# Generated by Django 3.0.3 on 2021-03-03 07:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_auto_20210302_1143'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddressTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Items',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('itemID', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Nutrition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calories', models.CharField(max_length=255)),
                ('sodium', models.CharField(max_length=255)),
                ('fat', models.CharField(max_length=255)),
                ('Carbs', models.CharField(max_length=255)),
                ('Protein', models.CharField(max_length=255)),
                ('itemID', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='myapp.Items')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('driver', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ShoppingCart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cartNumber', models.CharField(max_length=255)),
                ('items', models.ManyToManyField(blank=True, to='myapp.Items')),
            ],
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('storeName', models.CharField(max_length=255)),
                ('storeLocation', models.CharField(max_length=255)),
                ('items', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.Items')),
            ],
        ),
        migrations.RemoveField(
            model_name='account',
            name='address',
        ),
        migrations.AddField(
            model_name='account',
            name='primaryAddress',
            field=models.CharField(default=False, max_length=255),
        ),
        migrations.AlterField(
            model_name='account',
            name='email',
            field=models.CharField(default=False, max_length=255),
        ),
        migrations.AlterField(
            model_name='account',
            name='name',
            field=models.CharField(default=False, max_length=255),
        ),
        migrations.AlterField(
            model_name='account',
            name='phone',
            field=models.CharField(default=False, max_length=255),
        ),
        migrations.DeleteModel(
            name='Address',
        ),
        migrations.AddField(
            model_name='account',
            name='addressTable',
            field=models.ManyToManyField(default=False, to='myapp.AddressTable'),
        ),
        migrations.AddField(
            model_name='account',
            name='order',
            field=models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, to='myapp.Order'),
        ),
        migrations.AddField(
            model_name='account',
            name='shoppingCart',
            field=models.OneToOneField(default=False, on_delete=django.db.models.deletion.CASCADE, to='myapp.ShoppingCart'),
        ),
    ]
