# Generated by Django 3.1.7 on 2021-03-22 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_auto_20210318_0430'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='storeID',
            field=models.IntegerField(default=0),
        ),
    ]
