# Generated by Django 3.1.7 on 2021-03-22 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_auto_20210318_0430'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='id',
            field=models.IntegerField(default=0, max_length=30),
        ),
    ]
