# Generated by Django 3.1.7 on 2021-03-25 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_auto_20210323_2017'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shoppingcart',
            name='cartItems',
        ),
        migrations.AddField(
            model_name='shoppingcart',
            name='cartItems',
            field=models.ManyToManyField(to='myapp.CartItem'),
        ),
    ]
