# Generated by Django 3.1.7 on 2021-03-25 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_auto_20210325_1652'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='imgURL',
            field=models.CharField(default='https://image.shutterstock.com/image-photo/top-view-three-yellow-bananas-260nw-1875848530.jpg', max_length=255),
        ),
    ]
