# Generated by Django 3.1.7 on 2021-04-06 19:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_auto_20210325_2254'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='vendor',
        ),
        migrations.RemoveField(
            model_name='vendor',
            name='inventory',
        ),
        migrations.AddField(
            model_name='item',
            name='vendor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.vendor'),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='item',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.item'),
        ),
    ]
