# Generated by Django 3.1.7 on 2021-04-12 19:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('store', '0003_vendor_category'),
        ('myapp', '0011_auto_20210409_0518'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='store.item'),
        ),
        migrations.AlterUniqueTogether(
            name='cartitem',
            unique_together={('account', 'item')},
        ),
    ]
