# Generated by Django 3.1.7 on 2021-04-30 08:38

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_auto_20210430_0622'),
    ]

    operations = [
        
        migrations.DeleteModel(name='OrderItem'),
        migrations.DeleteModel(name='Order')
    ]
